export interface CountersDetail{
    
         SurveySubmittedViaEmail ?:number,
         SurveySubmittedViaSms ?:number,
         SurveySubmittedInstant ?:number,
         SurveyCheckedCount ?:number,
         SurveyCompltedCount ?:number,
         SurveySentCount ?:number,
         ServiceDone ?:number,
         SatisfiedInsFeedback ?:number,
         DisSatisfiedInsFeedback ?:number,
         SurveySubmittedTelephonic ?:number,
         PSFTotalDueCallCount ?:number,
         PSFTotalDoneCount ?:number,
         PSFTotalPendingCount ?:number,
         PSFTotalSatisfiedCount ?:number,
         PSFTotalDisSatisfiedCount ?:number,
         PSFSalesTotalDueCallCount ?:number,
         PSFSalesTotalDoneCount ?:number,
         PSFSalesTotalPendingCount ?:number,
         PSFSalesTotalSatisfiedCount ?:number,
         PSFSalesTotalDisSatisfiedCount ?:number,
         PendingIFCTABCount ?:number,
   
}